modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/DivineGenesis/Otherworld/issues"

[[mods]]
modId="otherworld"
version="BETA-1.0.0"
displayName="Otherworld"
displayURL="http://example.com/" #optional
logoFile="examplemod.png"
authors="Team DivineGenesis"
description='''A supernatural-type minecraft mod heavily influenced by Thaumcraft and Witchery amongst other games'''

[[dependencies.otherworld]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"