modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/DivineGenesis/Otherworld/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="http://example.com/" #optional
logoFile="examplemod.png"
authors="${mod_author}"
description='''${mod_description}'''

[[dependencies.otherworld]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"